#pragma once

#define DEBUG true
#define CONSOLE true
#define PROFILING true

#define THREAD_YIELD svcSleepThread(0)

#define NDSP_NUM_CHANNELS 24

#define CONTROLS_THREAD_PRIORITY 0x18
#define AUDIO_THREAD_PRIORITY 0x19
#define PHYSICS_THREAD_PRIORITY 0x1B
#define SCENELOADER_THREAD_PRIORITY 0x1C
#define MAIN_THREAD_PRIORITY 0x30

#define CORE0 0
#define APPCORE CORE0
#define CORE1 1
#define SYSCORE CORE1
#define CORE_ANY -1

#define SCENELOADER_THREAD_STACK_SZ (32 * 1024)
#define PHYSICS_THREAD_STACK_SZ (32 * 1024)
#define AUDIO_THREAD_STACK_SZ (32 * 1024)
#define CONTROLS_THREAD_STACK_SZ (32 * 1024)

#define PACKET_INFO_SIZE 8
#define MAX_PACKET_SIZE 32
#define PACKET_COUNT 1
#define PACKET_BUFFER_SIZE PACKET_COUNT * (PACKET_INFO_SIZE + MAX_PACKET_SIZE)
#define CPP_CONNECTION_POLLING_PERIOD_MS 0x08
#define CPP_POLLING_PERIOD_MS 0x32